updated PR-comment workflow files for controller test cases

diff --git a/.github/workflows/pr_comment.yml b/.github/workflows/pr_comment.yml
--- a/.github/workflows/pr_comment.yml
+++ b/.github/workflows/pr_comment.yml
@@ -59,11 +59,19 @@ jobs:
         continue-on-error: true  # Allow failure capturing
         run: |
           bundle exec rspec spec/models --format documentation > rspec_results.txt || true
+          bundle exec rspec spec/requests --format documentation >> rspec_results.txt || true
+
 
       - name: Extract Failed Tests
         if: always()  # Ensures this step runs regardless of test outcome
         run: |
-          awk '/Failures:/ {f=1} f && /^[[:space:]]*[0-9]+\)/ {print $0} f && /spec\// {print $0}' rspec_results.txt | tail -n 2 > failed_tests.txt && [ -s failed_tests.txt ] && echo "Above test cases failed" >> failed_tests.txt || echo "All tests passed." > failed_tests.txt
+          (
+          echo "Failing Model Test Cases:"
+          grep -E "^rspec ./spec/models/" rspec_results.txt
+          echo ""
+          echo "Failing Controller Test Cases:"
+          grep -E "^rspec ./spec/requests/" rspec_results.txt
+          ) > failed_tests.txt || echo "All tests passed." > failed_tests.txt
           echo "FAILED_TESTS<<EOF" >> $GITHUB_ENV
           cat failed_tests.txt >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
